[project]
name = "ogp-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "sqlmodel>=0.0.24",
    "uvicorn[standard]>=0.34.2",
]
